### ISSUE TITLE
Portugues (Portugal) Translation

### ISSUE THREAD

**Issue by cenourinha** [openfactory-ch/whmcs-oath-addon#14]
Please find below the text for the Portuguese - Portugal (portuguese-pt.php) translation:

`<?php

$_ADDONLANG['incorrect']='O seu código estava incorreto.';
$_ADDONLANG['enterCodeNote']='Digite o código gerado pela sua aplicação móvel.';
$_ADDONLANG['enterCode']='Insira o seu código';
$_ADDONLANG['btnLogin']='Validar Autenticação';
$_ADDONLANG['enterEmCode']='Digite o seu código de emergência';
$_ADDONLANG['emLogin']='Acesso de Emergência';
$_ADDONLANG['lostDevice']='Perdeu o seu dispositivo móvel?';
$_ADDONLANG['inactive']='O suporte a Autenticação de 2 Factores está desactivado.';
$_ADDONLANG['disabled']='A Autenticação de 2 Factores está descativada.';
$_ADDONLANG['btnEnable']='Activar a Autenticação de 2 Factores';
$_ADDONLANG['scanNote']='Por favor digitalize este código QR com a sua aplicação de autenticação móvel.';
$_ADDONLANG['unableScan']='Se não for possível fazer scan do QR code, use este código:';
$_ADDONLANG['verify']='Código de Verificação';
$_ADDONLANG['recomApp']='App Recomendada';
$_ADDONLANG['enabled']='Autenticação de 2 Factores está activa de momento.';
$_ADDONLANG['emCode']='O seu código de emergência é';
$_ADDONLANG['emCodeNote']='Poderá usar este código se perder o seu dispositivo móvel.';
$_ADDONLANG['btnSecret']='Ver Código';
$_ADDONLANG['emCodeNote2']='Anote esta informação. Não será exibida novamente.';
$_ADDONLANG['btnDisable']='Desactivar Autenticação de 2 Factores';
$_ADDONLANG['note']='Nota: Quaisquer sub-utilizadores com acesso à sua conta terão que fornecer um token de autenticação de 2 factores.';

?>
`

**Comment by cenourinha** [comment]
It would be great if we could also translate the menu name.

**Comment by dionysius** [comment]
Hi

Thank you for your contribution. I added your file and will be in the next release.

According menu name translation: The hooks don't load addon specific files (as of now). So the translation of the menu item is in the global whmcs language file:

```
[~/public_html]# grep twofactorauth lang/english.php
$_LANG['twofactorauth'] = "Two-Factor Authentication";
[~/public_html]# grep twofactorauth lang/german.php
$_LANG['twofactorauth'] = "Two-Factor Authentifizierung";
```

So add an entry for your language if missing there.
