### ISSUE TITLE
Persian Language

### ISSUE THREAD

**Issue by aminmahdi** [openfactory-ch/whmcs-oath-addon#5]
@dionysius 
I have add Persian (Farsi) language file.
https://github.com/aminmahdi/whmcs-oath-addon
Good Like  👍

**Comment by dionysius** [comment]
Hi, I can't find your suggested language file anywhere in your fork, did you forget to upload it?

**Comment by aminmahdi** [comment]
Hi, Yes, now  I have uploaded in my fork, name: "persian.php"

**Comment by aminmahdi** [comment]
dear @dionysius  please upload persian language

**Comment by dionysius** [comment]
I just added your file, thank you! See the release section.
