### ISSUE TITLE
My multicraft have an invalid index (and a custom apart from whmcs)

### ISSUE THREAD

**Issue by RealRunSpace** [openfactory-ch/whmcs-oath-addon#7]
Hello, my server index is broken and when always you try to access it, you get returned to the client area. There is anyway to redirect this to the client area directly, any way to allow my customers to use this without redirecting them to index?
Or you can help me fixing this index error I have with whmcs, thanks.

**Comment by dionysius** [comment]
Seems like I can't help you here much. I suggest you really to fix your index issue.

This question might give you the right direction: http://stackoverflow.com/questions/2384423/index-php-not-loading-by-default
